name: pkgcruft

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Run pkgcruft action
      uses: pkgcraft/pkgcruft-action@main
      with:
        pr-comments: false
